runtime: python39
env: standard
instance_class: F1
handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1

service_account: student-identification-portal@appspot.gserviceaccount.com