runtime: python39
entrypoint: bash -c 'curl --create-dirs -o $HOME/.postgresql/root.crt 'https://cockroachlabs.cloud/clusters/acd78f3b-f2e4-4563-9c61-62f8dcef8a25/cert' && python3 manage.py migrate --noinput && gunicorn -b :$PORT sipportal.wsgi:application'
env: standard
instance_class: F1
handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1

service_account: student-identification-portal@appspot.gserviceaccount.com