# Generated by Django 4.1 on 2022-08-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DecimalField(decimal_places=0, max_digits=4)),
                ('guardian_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('aadhar', models.DecimalField(decimal_places=0, max_digits=12)),
                ('gender', models.CharField(max_length=10)),
                ('active_status', models.CharField(max_length=20)),
                ('community', models.CharField(max_length=10)),
            ],
        ),
    ]
