# Generated by Django 4.1 on 2022-08-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institution_detail',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type_insti', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('dob', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('active_status', models.CharField(max_length=20)),
                ('community', models.CharField(max_length=10)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='degree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('discipline', models.CharField(max_length=20)),
                ('year_join', models.CharField(max_length=10)),
                ('year_leave', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.institution_detail')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.student_detail')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_marks', models.CharField(max_length=10)),
                ('obtained_marks', models.CharField(max_length=10)),
                ('credits', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=2)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.student_detail')),
            ],
        ),
    ]
