# Generated by Django 4.1 on 2022-08-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sid',
        ),
        migrations.AddField(
            model_name='course',
            name='did',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sip_db.degree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degree',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='year_leave',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
