# Generated by Django 4.1 on 2022-08-25 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_detail',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=50)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.student_detail')),
            ],
        ),
    ]
