# Generated by Django 4.1 on 2022-08-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='docreq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.institution_detail')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.student_detail')),
            ],
        ),
    ]
