# Generated by Django 4.1 on 2022-08-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0002_alter_user_details_aadhar_alter_user_details_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='institution_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type_insti', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='degree',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('discipline', models.CharField(max_length=20)),
                ('date_join', models.DateField()),
                ('date_leave', models.DateField()),
                ('grade', models.CharField(max_length=10)),
                ('insti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.institution_details')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_marks', models.CharField(max_length=10)),
                ('obtained_marks', models.CharField(max_length=10)),
                ('credits', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=2)),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_db.degree')),
            ],
        ),
    ]
