# Generated by Django 4.1 on 2022-08-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0002_docreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='i_id',
            new_name='iid',
        ),
    ]
