# Generated by Django 4.1 on 2022-08-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0002_account_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_detail',
            name='holder_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_detail',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
