# Generated by Django 4.1 on 2022-08-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0003_institution_details_alter_user_details_mobile_degree_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='institution_details',
            new_name='institution_detail',
        ),
        migrations.RenameModel(
            old_name='user_details',
            new_name='user_detail',
        ),
    ]
