# Generated by Django 4.1 on 2022-08-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0003_rename_i_id_degree_iid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='did',
            field=models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='sip_db.degree'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='iid',
            field=models.ForeignKey(db_column='iid', on_delete=django.db.models.deletion.CASCADE, to='sip_db.institution_detail'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='sip_db.student_detail'),
        ),
        migrations.AlterField(
            model_name='docreq',
            name='i_id',
            field=models.ForeignKey(db_column='i_id', on_delete=django.db.models.deletion.CASCADE, to='sip_db.institution_detail'),
        ),
        migrations.AlterField(
            model_name='docreq',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='sip_db.student_detail'),
        ),
    ]
