# Generated by Django 4.1 on 2022-08-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0003_rename_i_id_degree_iid'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_details',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=200)),
                ('permissions', models.CharField(max_length=100)),
            ],
        ),
    ]
