# Generated by Django 4.1 on 2022-08-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0004_alter_course_did_alter_degree_iid_alter_degree_sid_and_more'),
        ('sip_db', '0004_api_details'),
    ]

    operations = [
    ]
