# Generated by Django 4.1 on 2022-08-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0004_rename_institution_details_institution_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_detail',
            name='contact',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='institution_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
