# Generated by Django 4.1 on 2022-08-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0005_alter_institution_detail_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_detail',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
