# Generated by Django 4.1 on 2022-08-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0006_alter_institution_detail_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_detail',
            new_name='student_detail',
        ),
    ]
