# Generated by Django 4.1 on 2022-08-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0006_api_details_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_details',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
