# Generated by Django 4.1 on 2022-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0007_rename_user_detail_student_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
