# Generated by Django 4.1 on 2022-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0008_student_detail_address_student_detail_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='degree',
            name='insti_id',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='sid',
        ),
        migrations.AddField(
            model_name='degree',
            name='insti_id',
            field=models.ManyToManyField(to='sip_db.institution_detail'),
        ),
        migrations.AddField(
            model_name='degree',
            name='sid',
            field=models.ManyToManyField(to='sip_db.student_detail'),
        ),
    ]
