# Generated by Django 4.1 on 2022-08-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0009_alter_degree_id_remove_degree_insti_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree_id',
        ),
        migrations.AddField(
            model_name='course',
            name='sid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sip_db.student_detail'),
            preserve_default=False,
        ),
    ]
