# Generated by Django 4.1 on 2022-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0010_remove_course_degree_id_course_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution_detail',
            name='address',
            field=models.TextField(default='madras'),
            preserve_default=False,
        ),
    ]
