# Generated by Django 4.1 on 2022-08-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0011_institution_detail_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution_detail',
            name='address',
        ),
    ]
