# Generated by Django 4.1 on 2022-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip_db', '0012_remove_institution_detail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='i_id',
            field=models.ManyToManyField(to='sip_db.institution_detail'),
        ),
    ]
